package iecheck.yizhiwechat.framework.entity;

public class PhoneValite extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_valite.id
     *
     * @mbggenerated Tue Oct 04 19:31:57 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_valite.phone
     *
     * @mbggenerated Tue Oct 04 19:31:57 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_valite.valitecode
     *
     * @mbggenerated Tue Oct 04 19:31:57 CST 2016
     */
    private String valitecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column phone_valite.valite
     *
     * @mbggenerated Tue Oct 04 19:31:57 CST 2016
     */
    private Boolean valite;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_valite.id
     *
     * @return the value of phone_valite.id
     *
     * @mbggenerated Tue Oct 04 19:31:57 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_valite.id
     *
     * @param id the value for phone_valite.id
     *
     * @mbggenerated Tue Oct 04 19:31:57 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_valite.phone
     *
     * @return the value of phone_valite.phone
     *
     * @mbggenerated Tue Oct 04 19:31:57 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_valite.phone
     *
     * @param phone the value for phone_valite.phone
     *
     * @mbggenerated Tue Oct 04 19:31:57 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_valite.valitecode
     *
     * @return the value of phone_valite.valitecode
     *
     * @mbggenerated Tue Oct 04 19:31:57 CST 2016
     */
    public String getValitecode() {
        return valitecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_valite.valitecode
     *
     * @param valitecode the value for phone_valite.valitecode
     *
     * @mbggenerated Tue Oct 04 19:31:57 CST 2016
     */
    public void setValitecode(String valitecode) {
        this.valitecode = valitecode == null ? null : valitecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column phone_valite.valite
     *
     * @return the value of phone_valite.valite
     *
     * @mbggenerated Tue Oct 04 19:31:57 CST 2016
     */
    public Boolean getValite() {
        return valite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column phone_valite.valite
     *
     * @param valite the value for phone_valite.valite
     *
     * @mbggenerated Tue Oct 04 19:31:57 CST 2016
     */
    public void setValite(Boolean valite) {
        this.valite = valite;
    }
}