package iecheck.yizhiwechat.framework.entity;

public class WechatUserInfoYizhi extends BaseEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user_info_yizhi.id
     *
     * @mbggenerated Tue Oct 04 19:31:57 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user_info_yizhi.openid
     *
     * @mbggenerated Tue Oct 04 19:31:57 CST 2016
     */
    private String openid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user_info_yizhi.nickname
     *
     * @mbggenerated Tue Oct 04 19:31:57 CST 2016
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user_info_yizhi.headicon
     *
     * @mbggenerated Tue Oct 04 19:31:57 CST 2016
     */
    private String headicon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user_info_yizhi.phone
     *
     * @mbggenerated Tue Oct 04 19:31:57 CST 2016
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user_info_yizhi.id
     *
     * @return the value of wechat_user_info_yizhi.id
     *
     * @mbggenerated Tue Oct 04 19:31:57 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user_info_yizhi.id
     *
     * @param id the value for wechat_user_info_yizhi.id
     *
     * @mbggenerated Tue Oct 04 19:31:57 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user_info_yizhi.openid
     *
     * @return the value of wechat_user_info_yizhi.openid
     *
     * @mbggenerated Tue Oct 04 19:31:57 CST 2016
     */
    public String getOpenid() {
        return openid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user_info_yizhi.openid
     *
     * @param openid the value for wechat_user_info_yizhi.openid
     *
     * @mbggenerated Tue Oct 04 19:31:57 CST 2016
     */
    public void setOpenid(String openid) {
        this.openid = openid == null ? null : openid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user_info_yizhi.nickname
     *
     * @return the value of wechat_user_info_yizhi.nickname
     *
     * @mbggenerated Tue Oct 04 19:31:57 CST 2016
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user_info_yizhi.nickname
     *
     * @param nickname the value for wechat_user_info_yizhi.nickname
     *
     * @mbggenerated Tue Oct 04 19:31:57 CST 2016
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user_info_yizhi.headicon
     *
     * @return the value of wechat_user_info_yizhi.headicon
     *
     * @mbggenerated Tue Oct 04 19:31:57 CST 2016
     */
    public String getHeadicon() {
        return headicon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user_info_yizhi.headicon
     *
     * @param headicon the value for wechat_user_info_yizhi.headicon
     *
     * @mbggenerated Tue Oct 04 19:31:57 CST 2016
     */
    public void setHeadicon(String headicon) {
        this.headicon = headicon == null ? null : headicon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user_info_yizhi.phone
     *
     * @return the value of wechat_user_info_yizhi.phone
     *
     * @mbggenerated Tue Oct 04 19:31:57 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user_info_yizhi.phone
     *
     * @param phone the value for wechat_user_info_yizhi.phone
     *
     * @mbggenerated Tue Oct 04 19:31:57 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }
}